// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package aquasec

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type EnforcerGroups struct {
	pulumi.CustomResourceState

	AdmissionControl                          pulumi.BoolPtrOutput                  `pulumi:"admissionControl"`
	AllowKubeEnforcerAudit                    pulumi.BoolPtrOutput                  `pulumi:"allowKubeEnforcerAudit"`
	AllowedApplications                       pulumi.StringArrayOutput              `pulumi:"allowedApplications"`
	AllowedLabels                             pulumi.StringArrayOutput              `pulumi:"allowedLabels"`
	AllowedRegistries                         pulumi.StringArrayOutput              `pulumi:"allowedRegistries"`
	AntivirusProtection                       pulumi.BoolPtrOutput                  `pulumi:"antivirusProtection"`
	AquaVersion                               pulumi.StringOutput                   `pulumi:"aquaVersion"`
	AuditAll                                  pulumi.BoolPtrOutput                  `pulumi:"auditAll"`
	AutoCopySecrets                           pulumi.BoolPtrOutput                  `pulumi:"autoCopySecrets"`
	AutoDiscoverConfigureRegistries           pulumi.BoolPtrOutput                  `pulumi:"autoDiscoverConfigureRegistries"`
	AutoDiscoveryEnabled                      pulumi.BoolPtrOutput                  `pulumi:"autoDiscoveryEnabled"`
	AutoScanDiscoveredImagesRunningContainers pulumi.BoolPtrOutput                  `pulumi:"autoScanDiscoveredImagesRunningContainers"`
	BehavioralEngine                          pulumi.BoolPtrOutput                  `pulumi:"behavioralEngine"`
	BlockAdmissionControl                     pulumi.BoolPtrOutput                  `pulumi:"blockAdmissionControl"`
	Commands                                  EnforcerGroupsCommandArrayOutput      `pulumi:"commands"`
	ConnectedCount                            pulumi.IntOutput                      `pulumi:"connectedCount"`
	ContainerActivityProtection               pulumi.BoolPtrOutput                  `pulumi:"containerActivityProtection"`
	ContainerAntivirusProtection              pulumi.BoolPtrOutput                  `pulumi:"containerAntivirusProtection"`
	Description                               pulumi.StringPtrOutput                `pulumi:"description"`
	DisconnectedCount                         pulumi.IntOutput                      `pulumi:"disconnectedCount"`
	Enforce                                   pulumi.BoolPtrOutput                  `pulumi:"enforce"`
	EnforcerImageName                         pulumi.StringOutput                   `pulumi:"enforcerImageName"`
	GatewayAddress                            pulumi.StringOutput                   `pulumi:"gatewayAddress"`
	GatewayName                               pulumi.StringOutput                   `pulumi:"gatewayName"`
	Gateways                                  pulumi.StringArrayOutput              `pulumi:"gateways"`
	GroupId                                   pulumi.StringOutput                   `pulumi:"groupId"`
	HighVulns                                 pulumi.IntOutput                      `pulumi:"highVulns"`
	HostAssurance                             pulumi.BoolPtrOutput                  `pulumi:"hostAssurance"`
	HostBehavioralEngine                      pulumi.BoolPtrOutput                  `pulumi:"hostBehavioralEngine"`
	HostNetworkProtection                     pulumi.BoolPtrOutput                  `pulumi:"hostNetworkProtection"`
	HostOs                                    pulumi.StringOutput                   `pulumi:"hostOs"`
	HostProtection                            pulumi.BoolPtrOutput                  `pulumi:"hostProtection"`
	HostUserProtection                        pulumi.BoolPtrOutput                  `pulumi:"hostUserProtection"`
	Hostname                                  pulumi.StringOutput                   `pulumi:"hostname"`
	HostsCount                                pulumi.IntOutput                      `pulumi:"hostsCount"`
	ImageAssurance                            pulumi.BoolPtrOutput                  `pulumi:"imageAssurance"`
	InstallCommand                            pulumi.StringOutput                   `pulumi:"installCommand"`
	KubeBenchImageName                        pulumi.StringPtrOutput                `pulumi:"kubeBenchImageName"`
	LastUpdate                                pulumi.IntOutput                      `pulumi:"lastUpdate"`
	LogicalName                               pulumi.StringPtrOutput                `pulumi:"logicalName"`
	LowVulns                                  pulumi.IntOutput                      `pulumi:"lowVulns"`
	MedVulns                                  pulumi.IntOutput                      `pulumi:"medVulns"`
	MicroEnforcerCertsSecretsName             pulumi.StringPtrOutput                `pulumi:"microEnforcerCertsSecretsName"`
	MicroEnforcerImageName                    pulumi.StringPtrOutput                `pulumi:"microEnforcerImageName"`
	MicroEnforcerInjection                    pulumi.BoolPtrOutput                  `pulumi:"microEnforcerInjection"`
	MicroEnforcerSecretsName                  pulumi.StringPtrOutput                `pulumi:"microEnforcerSecretsName"`
	NegVulns                                  pulumi.IntOutput                      `pulumi:"negVulns"`
	NetworkActivityProtection                 pulumi.BoolPtrOutput                  `pulumi:"networkActivityProtection"`
	NetworkProtection                         pulumi.BoolPtrOutput                  `pulumi:"networkProtection"`
	Orchestrators                             EnforcerGroupsOrchestratorArrayOutput `pulumi:"orchestrators"`
	PasDeploymentLink                         pulumi.StringOutput                   `pulumi:"pasDeploymentLink"`
	Permission                                pulumi.StringPtrOutput                `pulumi:"permission"`
	RiskExplorerAutoDiscovery                 pulumi.BoolPtrOutput                  `pulumi:"riskExplorerAutoDiscovery"`
	RuntimePolicyName                         pulumi.StringOutput                   `pulumi:"runtimePolicyName"`
	RuntimeType                               pulumi.StringOutput                   `pulumi:"runtimeType"`
	SyncHostImages                            pulumi.BoolPtrOutput                  `pulumi:"syncHostImages"`
	SyscallEnabled                            pulumi.BoolPtrOutput                  `pulumi:"syscallEnabled"`
	Token                                     pulumi.StringOutput                   `pulumi:"token"`
	Type                                      pulumi.StringOutput                   `pulumi:"type"`
	UserAccessControl                         pulumi.BoolPtrOutput                  `pulumi:"userAccessControl"`
}

// NewEnforcerGroups registers a new resource with the given unique name, arguments, and options.
func NewEnforcerGroups(ctx *pulumi.Context,
	name string, args *EnforcerGroupsArgs, opts ...pulumi.ResourceOption) (*EnforcerGroups, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.GroupId == nil {
		return nil, errors.New("invalid value for required argument 'GroupId'")
	}
	if args.Orchestrators == nil {
		return nil, errors.New("invalid value for required argument 'Orchestrators'")
	}
	if args.Type == nil {
		return nil, errors.New("invalid value for required argument 'Type'")
	}
	var resource EnforcerGroups
	err := ctx.RegisterResource("aquasec:index/enforcerGroups:EnforcerGroups", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetEnforcerGroups gets an existing EnforcerGroups resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetEnforcerGroups(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *EnforcerGroupsState, opts ...pulumi.ResourceOption) (*EnforcerGroups, error) {
	var resource EnforcerGroups
	err := ctx.ReadResource("aquasec:index/enforcerGroups:EnforcerGroups", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering EnforcerGroups resources.
type enforcerGroupsState struct {
	AdmissionControl                          *bool                        `pulumi:"admissionControl"`
	AllowKubeEnforcerAudit                    *bool                        `pulumi:"allowKubeEnforcerAudit"`
	AllowedApplications                       []string                     `pulumi:"allowedApplications"`
	AllowedLabels                             []string                     `pulumi:"allowedLabels"`
	AllowedRegistries                         []string                     `pulumi:"allowedRegistries"`
	AntivirusProtection                       *bool                        `pulumi:"antivirusProtection"`
	AquaVersion                               *string                      `pulumi:"aquaVersion"`
	AuditAll                                  *bool                        `pulumi:"auditAll"`
	AutoCopySecrets                           *bool                        `pulumi:"autoCopySecrets"`
	AutoDiscoverConfigureRegistries           *bool                        `pulumi:"autoDiscoverConfigureRegistries"`
	AutoDiscoveryEnabled                      *bool                        `pulumi:"autoDiscoveryEnabled"`
	AutoScanDiscoveredImagesRunningContainers *bool                        `pulumi:"autoScanDiscoveredImagesRunningContainers"`
	BehavioralEngine                          *bool                        `pulumi:"behavioralEngine"`
	BlockAdmissionControl                     *bool                        `pulumi:"blockAdmissionControl"`
	Commands                                  []EnforcerGroupsCommand      `pulumi:"commands"`
	ConnectedCount                            *int                         `pulumi:"connectedCount"`
	ContainerActivityProtection               *bool                        `pulumi:"containerActivityProtection"`
	ContainerAntivirusProtection              *bool                        `pulumi:"containerAntivirusProtection"`
	Description                               *string                      `pulumi:"description"`
	DisconnectedCount                         *int                         `pulumi:"disconnectedCount"`
	Enforce                                   *bool                        `pulumi:"enforce"`
	EnforcerImageName                         *string                      `pulumi:"enforcerImageName"`
	GatewayAddress                            *string                      `pulumi:"gatewayAddress"`
	GatewayName                               *string                      `pulumi:"gatewayName"`
	Gateways                                  []string                     `pulumi:"gateways"`
	GroupId                                   *string                      `pulumi:"groupId"`
	HighVulns                                 *int                         `pulumi:"highVulns"`
	HostAssurance                             *bool                        `pulumi:"hostAssurance"`
	HostBehavioralEngine                      *bool                        `pulumi:"hostBehavioralEngine"`
	HostNetworkProtection                     *bool                        `pulumi:"hostNetworkProtection"`
	HostOs                                    *string                      `pulumi:"hostOs"`
	HostProtection                            *bool                        `pulumi:"hostProtection"`
	HostUserProtection                        *bool                        `pulumi:"hostUserProtection"`
	Hostname                                  *string                      `pulumi:"hostname"`
	HostsCount                                *int                         `pulumi:"hostsCount"`
	ImageAssurance                            *bool                        `pulumi:"imageAssurance"`
	InstallCommand                            *string                      `pulumi:"installCommand"`
	KubeBenchImageName                        *string                      `pulumi:"kubeBenchImageName"`
	LastUpdate                                *int                         `pulumi:"lastUpdate"`
	LogicalName                               *string                      `pulumi:"logicalName"`
	LowVulns                                  *int                         `pulumi:"lowVulns"`
	MedVulns                                  *int                         `pulumi:"medVulns"`
	MicroEnforcerCertsSecretsName             *string                      `pulumi:"microEnforcerCertsSecretsName"`
	MicroEnforcerImageName                    *string                      `pulumi:"microEnforcerImageName"`
	MicroEnforcerInjection                    *bool                        `pulumi:"microEnforcerInjection"`
	MicroEnforcerSecretsName                  *string                      `pulumi:"microEnforcerSecretsName"`
	NegVulns                                  *int                         `pulumi:"negVulns"`
	NetworkActivityProtection                 *bool                        `pulumi:"networkActivityProtection"`
	NetworkProtection                         *bool                        `pulumi:"networkProtection"`
	Orchestrators                             []EnforcerGroupsOrchestrator `pulumi:"orchestrators"`
	PasDeploymentLink                         *string                      `pulumi:"pasDeploymentLink"`
	Permission                                *string                      `pulumi:"permission"`
	RiskExplorerAutoDiscovery                 *bool                        `pulumi:"riskExplorerAutoDiscovery"`
	RuntimePolicyName                         *string                      `pulumi:"runtimePolicyName"`
	RuntimeType                               *string                      `pulumi:"runtimeType"`
	SyncHostImages                            *bool                        `pulumi:"syncHostImages"`
	SyscallEnabled                            *bool                        `pulumi:"syscallEnabled"`
	Token                                     *string                      `pulumi:"token"`
	Type                                      *string                      `pulumi:"type"`
	UserAccessControl                         *bool                        `pulumi:"userAccessControl"`
}

type EnforcerGroupsState struct {
	AdmissionControl                          pulumi.BoolPtrInput
	AllowKubeEnforcerAudit                    pulumi.BoolPtrInput
	AllowedApplications                       pulumi.StringArrayInput
	AllowedLabels                             pulumi.StringArrayInput
	AllowedRegistries                         pulumi.StringArrayInput
	AntivirusProtection                       pulumi.BoolPtrInput
	AquaVersion                               pulumi.StringPtrInput
	AuditAll                                  pulumi.BoolPtrInput
	AutoCopySecrets                           pulumi.BoolPtrInput
	AutoDiscoverConfigureRegistries           pulumi.BoolPtrInput
	AutoDiscoveryEnabled                      pulumi.BoolPtrInput
	AutoScanDiscoveredImagesRunningContainers pulumi.BoolPtrInput
	BehavioralEngine                          pulumi.BoolPtrInput
	BlockAdmissionControl                     pulumi.BoolPtrInput
	Commands                                  EnforcerGroupsCommandArrayInput
	ConnectedCount                            pulumi.IntPtrInput
	ContainerActivityProtection               pulumi.BoolPtrInput
	ContainerAntivirusProtection              pulumi.BoolPtrInput
	Description                               pulumi.StringPtrInput
	DisconnectedCount                         pulumi.IntPtrInput
	Enforce                                   pulumi.BoolPtrInput
	EnforcerImageName                         pulumi.StringPtrInput
	GatewayAddress                            pulumi.StringPtrInput
	GatewayName                               pulumi.StringPtrInput
	Gateways                                  pulumi.StringArrayInput
	GroupId                                   pulumi.StringPtrInput
	HighVulns                                 pulumi.IntPtrInput
	HostAssurance                             pulumi.BoolPtrInput
	HostBehavioralEngine                      pulumi.BoolPtrInput
	HostNetworkProtection                     pulumi.BoolPtrInput
	HostOs                                    pulumi.StringPtrInput
	HostProtection                            pulumi.BoolPtrInput
	HostUserProtection                        pulumi.BoolPtrInput
	Hostname                                  pulumi.StringPtrInput
	HostsCount                                pulumi.IntPtrInput
	ImageAssurance                            pulumi.BoolPtrInput
	InstallCommand                            pulumi.StringPtrInput
	KubeBenchImageName                        pulumi.StringPtrInput
	LastUpdate                                pulumi.IntPtrInput
	LogicalName                               pulumi.StringPtrInput
	LowVulns                                  pulumi.IntPtrInput
	MedVulns                                  pulumi.IntPtrInput
	MicroEnforcerCertsSecretsName             pulumi.StringPtrInput
	MicroEnforcerImageName                    pulumi.StringPtrInput
	MicroEnforcerInjection                    pulumi.BoolPtrInput
	MicroEnforcerSecretsName                  pulumi.StringPtrInput
	NegVulns                                  pulumi.IntPtrInput
	NetworkActivityProtection                 pulumi.BoolPtrInput
	NetworkProtection                         pulumi.BoolPtrInput
	Orchestrators                             EnforcerGroupsOrchestratorArrayInput
	PasDeploymentLink                         pulumi.StringPtrInput
	Permission                                pulumi.StringPtrInput
	RiskExplorerAutoDiscovery                 pulumi.BoolPtrInput
	RuntimePolicyName                         pulumi.StringPtrInput
	RuntimeType                               pulumi.StringPtrInput
	SyncHostImages                            pulumi.BoolPtrInput
	SyscallEnabled                            pulumi.BoolPtrInput
	Token                                     pulumi.StringPtrInput
	Type                                      pulumi.StringPtrInput
	UserAccessControl                         pulumi.BoolPtrInput
}

func (EnforcerGroupsState) ElementType() reflect.Type {
	return reflect.TypeOf((*enforcerGroupsState)(nil)).Elem()
}

type enforcerGroupsArgs struct {
	AdmissionControl                          *bool                        `pulumi:"admissionControl"`
	AllowKubeEnforcerAudit                    *bool                        `pulumi:"allowKubeEnforcerAudit"`
	AllowedApplications                       []string                     `pulumi:"allowedApplications"`
	AllowedLabels                             []string                     `pulumi:"allowedLabels"`
	AllowedRegistries                         []string                     `pulumi:"allowedRegistries"`
	AntivirusProtection                       *bool                        `pulumi:"antivirusProtection"`
	AuditAll                                  *bool                        `pulumi:"auditAll"`
	AutoCopySecrets                           *bool                        `pulumi:"autoCopySecrets"`
	AutoDiscoverConfigureRegistries           *bool                        `pulumi:"autoDiscoverConfigureRegistries"`
	AutoDiscoveryEnabled                      *bool                        `pulumi:"autoDiscoveryEnabled"`
	AutoScanDiscoveredImagesRunningContainers *bool                        `pulumi:"autoScanDiscoveredImagesRunningContainers"`
	BehavioralEngine                          *bool                        `pulumi:"behavioralEngine"`
	BlockAdmissionControl                     *bool                        `pulumi:"blockAdmissionControl"`
	ContainerActivityProtection               *bool                        `pulumi:"containerActivityProtection"`
	ContainerAntivirusProtection              *bool                        `pulumi:"containerAntivirusProtection"`
	Description                               *string                      `pulumi:"description"`
	Enforce                                   *bool                        `pulumi:"enforce"`
	Gateways                                  []string                     `pulumi:"gateways"`
	GroupId                                   string                       `pulumi:"groupId"`
	HostAssurance                             *bool                        `pulumi:"hostAssurance"`
	HostBehavioralEngine                      *bool                        `pulumi:"hostBehavioralEngine"`
	HostNetworkProtection                     *bool                        `pulumi:"hostNetworkProtection"`
	HostProtection                            *bool                        `pulumi:"hostProtection"`
	HostUserProtection                        *bool                        `pulumi:"hostUserProtection"`
	ImageAssurance                            *bool                        `pulumi:"imageAssurance"`
	KubeBenchImageName                        *string                      `pulumi:"kubeBenchImageName"`
	LogicalName                               *string                      `pulumi:"logicalName"`
	MicroEnforcerCertsSecretsName             *string                      `pulumi:"microEnforcerCertsSecretsName"`
	MicroEnforcerImageName                    *string                      `pulumi:"microEnforcerImageName"`
	MicroEnforcerInjection                    *bool                        `pulumi:"microEnforcerInjection"`
	MicroEnforcerSecretsName                  *string                      `pulumi:"microEnforcerSecretsName"`
	NetworkActivityProtection                 *bool                        `pulumi:"networkActivityProtection"`
	NetworkProtection                         *bool                        `pulumi:"networkProtection"`
	Orchestrators                             []EnforcerGroupsOrchestrator `pulumi:"orchestrators"`
	Permission                                *string                      `pulumi:"permission"`
	RiskExplorerAutoDiscovery                 *bool                        `pulumi:"riskExplorerAutoDiscovery"`
	SyncHostImages                            *bool                        `pulumi:"syncHostImages"`
	SyscallEnabled                            *bool                        `pulumi:"syscallEnabled"`
	Type                                      string                       `pulumi:"type"`
	UserAccessControl                         *bool                        `pulumi:"userAccessControl"`
}

// The set of arguments for constructing a EnforcerGroups resource.
type EnforcerGroupsArgs struct {
	AdmissionControl                          pulumi.BoolPtrInput
	AllowKubeEnforcerAudit                    pulumi.BoolPtrInput
	AllowedApplications                       pulumi.StringArrayInput
	AllowedLabels                             pulumi.StringArrayInput
	AllowedRegistries                         pulumi.StringArrayInput
	AntivirusProtection                       pulumi.BoolPtrInput
	AuditAll                                  pulumi.BoolPtrInput
	AutoCopySecrets                           pulumi.BoolPtrInput
	AutoDiscoverConfigureRegistries           pulumi.BoolPtrInput
	AutoDiscoveryEnabled                      pulumi.BoolPtrInput
	AutoScanDiscoveredImagesRunningContainers pulumi.BoolPtrInput
	BehavioralEngine                          pulumi.BoolPtrInput
	BlockAdmissionControl                     pulumi.BoolPtrInput
	ContainerActivityProtection               pulumi.BoolPtrInput
	ContainerAntivirusProtection              pulumi.BoolPtrInput
	Description                               pulumi.StringPtrInput
	Enforce                                   pulumi.BoolPtrInput
	Gateways                                  pulumi.StringArrayInput
	GroupId                                   pulumi.StringInput
	HostAssurance                             pulumi.BoolPtrInput
	HostBehavioralEngine                      pulumi.BoolPtrInput
	HostNetworkProtection                     pulumi.BoolPtrInput
	HostProtection                            pulumi.BoolPtrInput
	HostUserProtection                        pulumi.BoolPtrInput
	ImageAssurance                            pulumi.BoolPtrInput
	KubeBenchImageName                        pulumi.StringPtrInput
	LogicalName                               pulumi.StringPtrInput
	MicroEnforcerCertsSecretsName             pulumi.StringPtrInput
	MicroEnforcerImageName                    pulumi.StringPtrInput
	MicroEnforcerInjection                    pulumi.BoolPtrInput
	MicroEnforcerSecretsName                  pulumi.StringPtrInput
	NetworkActivityProtection                 pulumi.BoolPtrInput
	NetworkProtection                         pulumi.BoolPtrInput
	Orchestrators                             EnforcerGroupsOrchestratorArrayInput
	Permission                                pulumi.StringPtrInput
	RiskExplorerAutoDiscovery                 pulumi.BoolPtrInput
	SyncHostImages                            pulumi.BoolPtrInput
	SyscallEnabled                            pulumi.BoolPtrInput
	Type                                      pulumi.StringInput
	UserAccessControl                         pulumi.BoolPtrInput
}

func (EnforcerGroupsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*enforcerGroupsArgs)(nil)).Elem()
}

type EnforcerGroupsInput interface {
	pulumi.Input

	ToEnforcerGroupsOutput() EnforcerGroupsOutput
	ToEnforcerGroupsOutputWithContext(ctx context.Context) EnforcerGroupsOutput
}

func (*EnforcerGroups) ElementType() reflect.Type {
	return reflect.TypeOf((**EnforcerGroups)(nil)).Elem()
}

func (i *EnforcerGroups) ToEnforcerGroupsOutput() EnforcerGroupsOutput {
	return i.ToEnforcerGroupsOutputWithContext(context.Background())
}

func (i *EnforcerGroups) ToEnforcerGroupsOutputWithContext(ctx context.Context) EnforcerGroupsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EnforcerGroupsOutput)
}

// EnforcerGroupsArrayInput is an input type that accepts EnforcerGroupsArray and EnforcerGroupsArrayOutput values.
// You can construct a concrete instance of `EnforcerGroupsArrayInput` via:
//
//          EnforcerGroupsArray{ EnforcerGroupsArgs{...} }
type EnforcerGroupsArrayInput interface {
	pulumi.Input

	ToEnforcerGroupsArrayOutput() EnforcerGroupsArrayOutput
	ToEnforcerGroupsArrayOutputWithContext(context.Context) EnforcerGroupsArrayOutput
}

type EnforcerGroupsArray []EnforcerGroupsInput

func (EnforcerGroupsArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*EnforcerGroups)(nil)).Elem()
}

func (i EnforcerGroupsArray) ToEnforcerGroupsArrayOutput() EnforcerGroupsArrayOutput {
	return i.ToEnforcerGroupsArrayOutputWithContext(context.Background())
}

func (i EnforcerGroupsArray) ToEnforcerGroupsArrayOutputWithContext(ctx context.Context) EnforcerGroupsArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EnforcerGroupsArrayOutput)
}

// EnforcerGroupsMapInput is an input type that accepts EnforcerGroupsMap and EnforcerGroupsMapOutput values.
// You can construct a concrete instance of `EnforcerGroupsMapInput` via:
//
//          EnforcerGroupsMap{ "key": EnforcerGroupsArgs{...} }
type EnforcerGroupsMapInput interface {
	pulumi.Input

	ToEnforcerGroupsMapOutput() EnforcerGroupsMapOutput
	ToEnforcerGroupsMapOutputWithContext(context.Context) EnforcerGroupsMapOutput
}

type EnforcerGroupsMap map[string]EnforcerGroupsInput

func (EnforcerGroupsMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*EnforcerGroups)(nil)).Elem()
}

func (i EnforcerGroupsMap) ToEnforcerGroupsMapOutput() EnforcerGroupsMapOutput {
	return i.ToEnforcerGroupsMapOutputWithContext(context.Background())
}

func (i EnforcerGroupsMap) ToEnforcerGroupsMapOutputWithContext(ctx context.Context) EnforcerGroupsMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EnforcerGroupsMapOutput)
}

type EnforcerGroupsOutput struct{ *pulumi.OutputState }

func (EnforcerGroupsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**EnforcerGroups)(nil)).Elem()
}

func (o EnforcerGroupsOutput) ToEnforcerGroupsOutput() EnforcerGroupsOutput {
	return o
}

func (o EnforcerGroupsOutput) ToEnforcerGroupsOutputWithContext(ctx context.Context) EnforcerGroupsOutput {
	return o
}

type EnforcerGroupsArrayOutput struct{ *pulumi.OutputState }

func (EnforcerGroupsArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*EnforcerGroups)(nil)).Elem()
}

func (o EnforcerGroupsArrayOutput) ToEnforcerGroupsArrayOutput() EnforcerGroupsArrayOutput {
	return o
}

func (o EnforcerGroupsArrayOutput) ToEnforcerGroupsArrayOutputWithContext(ctx context.Context) EnforcerGroupsArrayOutput {
	return o
}

func (o EnforcerGroupsArrayOutput) Index(i pulumi.IntInput) EnforcerGroupsOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *EnforcerGroups {
		return vs[0].([]*EnforcerGroups)[vs[1].(int)]
	}).(EnforcerGroupsOutput)
}

type EnforcerGroupsMapOutput struct{ *pulumi.OutputState }

func (EnforcerGroupsMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*EnforcerGroups)(nil)).Elem()
}

func (o EnforcerGroupsMapOutput) ToEnforcerGroupsMapOutput() EnforcerGroupsMapOutput {
	return o
}

func (o EnforcerGroupsMapOutput) ToEnforcerGroupsMapOutputWithContext(ctx context.Context) EnforcerGroupsMapOutput {
	return o
}

func (o EnforcerGroupsMapOutput) MapIndex(k pulumi.StringInput) EnforcerGroupsOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *EnforcerGroups {
		return vs[0].(map[string]*EnforcerGroups)[vs[1].(string)]
	}).(EnforcerGroupsOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*EnforcerGroupsInput)(nil)).Elem(), &EnforcerGroups{})
	pulumi.RegisterInputType(reflect.TypeOf((*EnforcerGroupsArrayInput)(nil)).Elem(), EnforcerGroupsArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*EnforcerGroupsMapInput)(nil)).Elem(), EnforcerGroupsMap{})
	pulumi.RegisterOutputType(EnforcerGroupsOutput{})
	pulumi.RegisterOutputType(EnforcerGroupsArrayOutput{})
	pulumi.RegisterOutputType(EnforcerGroupsMapOutput{})
}
