// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package aquasec

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupImageAssurancePolicy(ctx *pulumi.Context, args *LookupImageAssurancePolicyArgs, opts ...pulumi.InvokeOption) (*LookupImageAssurancePolicyResult, error) {
	var rv LookupImageAssurancePolicyResult
	err := ctx.Invoke("aquasec:index/getImageAssurancePolicy:getImageAssurancePolicy", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getImageAssurancePolicy.
type LookupImageAssurancePolicyArgs struct {
	MaximumScoreExcludeNoFix *bool  `pulumi:"maximumScoreExcludeNoFix"`
	Name                     string `pulumi:"name"`
}

// A collection of values returned by getImageAssurancePolicy.
type LookupImageAssurancePolicyResult struct {
	AllowedImages                    []string                                `pulumi:"allowedImages"`
	ApplicationScopes                []string                                `pulumi:"applicationScopes"`
	AssuranceType                    string                                  `pulumi:"assuranceType"`
	AuditOnFailure                   bool                                    `pulumi:"auditOnFailure"`
	Author                           string                                  `pulumi:"author"`
	AutoScanConfigured               bool                                    `pulumi:"autoScanConfigured"`
	AutoScanEnabled                  bool                                    `pulumi:"autoScanEnabled"`
	AutoScanTimes                    []GetImageAssurancePolicyAutoScanTime   `pulumi:"autoScanTimes"`
	BlacklistPermissions             []string                                `pulumi:"blacklistPermissions"`
	BlacklistPermissionsEnabled      bool                                    `pulumi:"blacklistPermissionsEnabled"`
	BlacklistedLicenses              []string                                `pulumi:"blacklistedLicenses"`
	BlacklistedLicensesEnabled       bool                                    `pulumi:"blacklistedLicensesEnabled"`
	BlockFailed                      bool                                    `pulumi:"blockFailed"`
	ControlExcludeNoFix              bool                                    `pulumi:"controlExcludeNoFix"`
	CustomChecks                     []GetImageAssurancePolicyCustomCheck    `pulumi:"customChecks"`
	CustomChecksEnabled              bool                                    `pulumi:"customChecksEnabled"`
	CustomSeverityEnabled            bool                                    `pulumi:"customSeverityEnabled"`
	CvesBlackListEnabled             bool                                    `pulumi:"cvesBlackListEnabled"`
	CvesBlackLists                   []string                                `pulumi:"cvesBlackLists"`
	CvesWhiteListEnabled             bool                                    `pulumi:"cvesWhiteListEnabled"`
	CvesWhiteLists                   []string                                `pulumi:"cvesWhiteLists"`
	CvssSeverity                     string                                  `pulumi:"cvssSeverity"`
	CvssSeverityEnabled              bool                                    `pulumi:"cvssSeverityEnabled"`
	CvssSeverityExcludeNoFix         bool                                    `pulumi:"cvssSeverityExcludeNoFix"`
	Description                      string                                  `pulumi:"description"`
	DisallowMalware                  bool                                    `pulumi:"disallowMalware"`
	DockerCisEnabled                 bool                                    `pulumi:"dockerCisEnabled"`
	Domain                           string                                  `pulumi:"domain"`
	DomainName                       string                                  `pulumi:"domainName"`
	DtaEnabled                       bool                                    `pulumi:"dtaEnabled"`
	DtaSeverity                      string                                  `pulumi:"dtaSeverity"`
	Enabled                          bool                                    `pulumi:"enabled"`
	Enforce                          bool                                    `pulumi:"enforce"`
	EnforceAfterDays                 int                                     `pulumi:"enforceAfterDays"`
	EnforceExcessivePermissions      bool                                    `pulumi:"enforceExcessivePermissions"`
	ExceptionalMonitoredMalwarePaths []string                                `pulumi:"exceptionalMonitoredMalwarePaths"`
	FailCicd                         bool                                    `pulumi:"failCicd"`
	ForbiddenLabels                  []GetImageAssurancePolicyForbiddenLabel `pulumi:"forbiddenLabels"`
	ForbiddenLabelsEnabled           bool                                    `pulumi:"forbiddenLabelsEnabled"`
	ForceMicroenforcer               bool                                    `pulumi:"forceMicroenforcer"`
	FunctionIntegrityEnabled         bool                                    `pulumi:"functionIntegrityEnabled"`
	// The ID of this resource.
	Id                               string                                     `pulumi:"id"`
	IgnoreRecentlyPublishedVln       bool                                       `pulumi:"ignoreRecentlyPublishedVln"`
	IgnoreRecentlyPublishedVlnPeriod int                                        `pulumi:"ignoreRecentlyPublishedVlnPeriod"`
	IgnoreRiskResourcesEnabled       bool                                       `pulumi:"ignoreRiskResourcesEnabled"`
	IgnoredRiskResources             []string                                   `pulumi:"ignoredRiskResources"`
	Images                           []string                                   `pulumi:"images"`
	KubeCisEnabled                   bool                                       `pulumi:"kubeCisEnabled"`
	Labels                           []string                                   `pulumi:"labels"`
	MalwareAction                    string                                     `pulumi:"malwareAction"`
	MaximumScore                     float64                                    `pulumi:"maximumScore"`
	MaximumScoreEnabled              bool                                       `pulumi:"maximumScoreEnabled"`
	MaximumScoreExcludeNoFix         *bool                                      `pulumi:"maximumScoreExcludeNoFix"`
	MonitoredMalwarePaths            []string                                   `pulumi:"monitoredMalwarePaths"`
	Name                             string                                     `pulumi:"name"`
	OnlyNoneRootUsers                bool                                       `pulumi:"onlyNoneRootUsers"`
	PackagesBlackListEnabled         bool                                       `pulumi:"packagesBlackListEnabled"`
	PackagesBlackLists               []GetImageAssurancePolicyPackagesBlackList `pulumi:"packagesBlackLists"`
	PackagesWhiteListEnabled         bool                                       `pulumi:"packagesWhiteListEnabled"`
	PackagesWhiteLists               []GetImageAssurancePolicyPackagesWhiteList `pulumi:"packagesWhiteLists"`
	PartialResultsImageFail          bool                                       `pulumi:"partialResultsImageFail"`
	ReadOnly                         bool                                       `pulumi:"readOnly"`
	Registries                       []string                                   `pulumi:"registries"`
	Registry                         string                                     `pulumi:"registry"`
	RequiredLabels                   []GetImageAssurancePolicyRequiredLabel     `pulumi:"requiredLabels"`
	RequiredLabelsEnabled            bool                                       `pulumi:"requiredLabelsEnabled"`
	ScanNfsMounts                    bool                                       `pulumi:"scanNfsMounts"`
	ScanSensitiveData                bool                                       `pulumi:"scanSensitiveData"`
	ScapEnabled                      bool                                       `pulumi:"scapEnabled"`
	ScapFiles                        []string                                   `pulumi:"scapFiles"`
	Scopes                           []GetImageAssurancePolicyScope             `pulumi:"scopes"`
	TrustedBaseImages                []GetImageAssurancePolicyTrustedBaseImage  `pulumi:"trustedBaseImages"`
	TrustedBaseImagesEnabled         bool                                       `pulumi:"trustedBaseImagesEnabled"`
	WhitelistedLicenses              []string                                   `pulumi:"whitelistedLicenses"`
	WhitelistedLicensesEnabled       bool                                       `pulumi:"whitelistedLicensesEnabled"`
}

func LookupImageAssurancePolicyOutput(ctx *pulumi.Context, args LookupImageAssurancePolicyOutputArgs, opts ...pulumi.InvokeOption) LookupImageAssurancePolicyResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupImageAssurancePolicyResult, error) {
			args := v.(LookupImageAssurancePolicyArgs)
			r, err := LookupImageAssurancePolicy(ctx, &args, opts...)
			return *r, err
		}).(LookupImageAssurancePolicyResultOutput)
}

// A collection of arguments for invoking getImageAssurancePolicy.
type LookupImageAssurancePolicyOutputArgs struct {
	MaximumScoreExcludeNoFix pulumi.BoolPtrInput `pulumi:"maximumScoreExcludeNoFix"`
	Name                     pulumi.StringInput  `pulumi:"name"`
}

func (LookupImageAssurancePolicyOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupImageAssurancePolicyArgs)(nil)).Elem()
}

// A collection of values returned by getImageAssurancePolicy.
type LookupImageAssurancePolicyResultOutput struct{ *pulumi.OutputState }

func (LookupImageAssurancePolicyResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupImageAssurancePolicyResult)(nil)).Elem()
}

func (o LookupImageAssurancePolicyResultOutput) ToLookupImageAssurancePolicyResultOutput() LookupImageAssurancePolicyResultOutput {
	return o
}

func (o LookupImageAssurancePolicyResultOutput) ToLookupImageAssurancePolicyResultOutputWithContext(ctx context.Context) LookupImageAssurancePolicyResultOutput {
	return o
}

func (o LookupImageAssurancePolicyResultOutput) AllowedImages() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) []string { return v.AllowedImages }).(pulumi.StringArrayOutput)
}

func (o LookupImageAssurancePolicyResultOutput) ApplicationScopes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) []string { return v.ApplicationScopes }).(pulumi.StringArrayOutput)
}

func (o LookupImageAssurancePolicyResultOutput) AssuranceType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) string { return v.AssuranceType }).(pulumi.StringOutput)
}

func (o LookupImageAssurancePolicyResultOutput) AuditOnFailure() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.AuditOnFailure }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) Author() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) string { return v.Author }).(pulumi.StringOutput)
}

func (o LookupImageAssurancePolicyResultOutput) AutoScanConfigured() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.AutoScanConfigured }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) AutoScanEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.AutoScanEnabled }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) AutoScanTimes() GetImageAssurancePolicyAutoScanTimeArrayOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) []GetImageAssurancePolicyAutoScanTime { return v.AutoScanTimes }).(GetImageAssurancePolicyAutoScanTimeArrayOutput)
}

func (o LookupImageAssurancePolicyResultOutput) BlacklistPermissions() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) []string { return v.BlacklistPermissions }).(pulumi.StringArrayOutput)
}

func (o LookupImageAssurancePolicyResultOutput) BlacklistPermissionsEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.BlacklistPermissionsEnabled }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) BlacklistedLicenses() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) []string { return v.BlacklistedLicenses }).(pulumi.StringArrayOutput)
}

func (o LookupImageAssurancePolicyResultOutput) BlacklistedLicensesEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.BlacklistedLicensesEnabled }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) BlockFailed() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.BlockFailed }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) ControlExcludeNoFix() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.ControlExcludeNoFix }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) CustomChecks() GetImageAssurancePolicyCustomCheckArrayOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) []GetImageAssurancePolicyCustomCheck { return v.CustomChecks }).(GetImageAssurancePolicyCustomCheckArrayOutput)
}

func (o LookupImageAssurancePolicyResultOutput) CustomChecksEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.CustomChecksEnabled }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) CustomSeverityEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.CustomSeverityEnabled }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) CvesBlackListEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.CvesBlackListEnabled }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) CvesBlackLists() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) []string { return v.CvesBlackLists }).(pulumi.StringArrayOutput)
}

func (o LookupImageAssurancePolicyResultOutput) CvesWhiteListEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.CvesWhiteListEnabled }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) CvesWhiteLists() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) []string { return v.CvesWhiteLists }).(pulumi.StringArrayOutput)
}

func (o LookupImageAssurancePolicyResultOutput) CvssSeverity() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) string { return v.CvssSeverity }).(pulumi.StringOutput)
}

func (o LookupImageAssurancePolicyResultOutput) CvssSeverityEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.CvssSeverityEnabled }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) CvssSeverityExcludeNoFix() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.CvssSeverityExcludeNoFix }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupImageAssurancePolicyResultOutput) DisallowMalware() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.DisallowMalware }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) DockerCisEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.DockerCisEnabled }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) string { return v.Domain }).(pulumi.StringOutput)
}

func (o LookupImageAssurancePolicyResultOutput) DomainName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) string { return v.DomainName }).(pulumi.StringOutput)
}

func (o LookupImageAssurancePolicyResultOutput) DtaEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.DtaEnabled }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) DtaSeverity() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) string { return v.DtaSeverity }).(pulumi.StringOutput)
}

func (o LookupImageAssurancePolicyResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) Enforce() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.Enforce }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) EnforceAfterDays() pulumi.IntOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) int { return v.EnforceAfterDays }).(pulumi.IntOutput)
}

func (o LookupImageAssurancePolicyResultOutput) EnforceExcessivePermissions() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.EnforceExcessivePermissions }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) ExceptionalMonitoredMalwarePaths() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) []string { return v.ExceptionalMonitoredMalwarePaths }).(pulumi.StringArrayOutput)
}

func (o LookupImageAssurancePolicyResultOutput) FailCicd() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.FailCicd }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) ForbiddenLabels() GetImageAssurancePolicyForbiddenLabelArrayOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) []GetImageAssurancePolicyForbiddenLabel {
		return v.ForbiddenLabels
	}).(GetImageAssurancePolicyForbiddenLabelArrayOutput)
}

func (o LookupImageAssurancePolicyResultOutput) ForbiddenLabelsEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.ForbiddenLabelsEnabled }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) ForceMicroenforcer() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.ForceMicroenforcer }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) FunctionIntegrityEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.FunctionIntegrityEnabled }).(pulumi.BoolOutput)
}

// The ID of this resource.
func (o LookupImageAssurancePolicyResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupImageAssurancePolicyResultOutput) IgnoreRecentlyPublishedVln() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.IgnoreRecentlyPublishedVln }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) IgnoreRecentlyPublishedVlnPeriod() pulumi.IntOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) int { return v.IgnoreRecentlyPublishedVlnPeriod }).(pulumi.IntOutput)
}

func (o LookupImageAssurancePolicyResultOutput) IgnoreRiskResourcesEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.IgnoreRiskResourcesEnabled }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) IgnoredRiskResources() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) []string { return v.IgnoredRiskResources }).(pulumi.StringArrayOutput)
}

func (o LookupImageAssurancePolicyResultOutput) Images() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) []string { return v.Images }).(pulumi.StringArrayOutput)
}

func (o LookupImageAssurancePolicyResultOutput) KubeCisEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.KubeCisEnabled }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) Labels() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) []string { return v.Labels }).(pulumi.StringArrayOutput)
}

func (o LookupImageAssurancePolicyResultOutput) MalwareAction() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) string { return v.MalwareAction }).(pulumi.StringOutput)
}

func (o LookupImageAssurancePolicyResultOutput) MaximumScore() pulumi.Float64Output {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) float64 { return v.MaximumScore }).(pulumi.Float64Output)
}

func (o LookupImageAssurancePolicyResultOutput) MaximumScoreEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.MaximumScoreEnabled }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) MaximumScoreExcludeNoFix() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) *bool { return v.MaximumScoreExcludeNoFix }).(pulumi.BoolPtrOutput)
}

func (o LookupImageAssurancePolicyResultOutput) MonitoredMalwarePaths() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) []string { return v.MonitoredMalwarePaths }).(pulumi.StringArrayOutput)
}

func (o LookupImageAssurancePolicyResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupImageAssurancePolicyResultOutput) OnlyNoneRootUsers() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.OnlyNoneRootUsers }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) PackagesBlackListEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.PackagesBlackListEnabled }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) PackagesBlackLists() GetImageAssurancePolicyPackagesBlackListArrayOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) []GetImageAssurancePolicyPackagesBlackList {
		return v.PackagesBlackLists
	}).(GetImageAssurancePolicyPackagesBlackListArrayOutput)
}

func (o LookupImageAssurancePolicyResultOutput) PackagesWhiteListEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.PackagesWhiteListEnabled }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) PackagesWhiteLists() GetImageAssurancePolicyPackagesWhiteListArrayOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) []GetImageAssurancePolicyPackagesWhiteList {
		return v.PackagesWhiteLists
	}).(GetImageAssurancePolicyPackagesWhiteListArrayOutput)
}

func (o LookupImageAssurancePolicyResultOutput) PartialResultsImageFail() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.PartialResultsImageFail }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) ReadOnly() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.ReadOnly }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) Registries() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) []string { return v.Registries }).(pulumi.StringArrayOutput)
}

func (o LookupImageAssurancePolicyResultOutput) Registry() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) string { return v.Registry }).(pulumi.StringOutput)
}

func (o LookupImageAssurancePolicyResultOutput) RequiredLabels() GetImageAssurancePolicyRequiredLabelArrayOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) []GetImageAssurancePolicyRequiredLabel {
		return v.RequiredLabels
	}).(GetImageAssurancePolicyRequiredLabelArrayOutput)
}

func (o LookupImageAssurancePolicyResultOutput) RequiredLabelsEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.RequiredLabelsEnabled }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) ScanNfsMounts() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.ScanNfsMounts }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) ScanSensitiveData() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.ScanSensitiveData }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) ScapEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.ScapEnabled }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) ScapFiles() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) []string { return v.ScapFiles }).(pulumi.StringArrayOutput)
}

func (o LookupImageAssurancePolicyResultOutput) Scopes() GetImageAssurancePolicyScopeArrayOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) []GetImageAssurancePolicyScope { return v.Scopes }).(GetImageAssurancePolicyScopeArrayOutput)
}

func (o LookupImageAssurancePolicyResultOutput) TrustedBaseImages() GetImageAssurancePolicyTrustedBaseImageArrayOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) []GetImageAssurancePolicyTrustedBaseImage {
		return v.TrustedBaseImages
	}).(GetImageAssurancePolicyTrustedBaseImageArrayOutput)
}

func (o LookupImageAssurancePolicyResultOutput) TrustedBaseImagesEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.TrustedBaseImagesEnabled }).(pulumi.BoolOutput)
}

func (o LookupImageAssurancePolicyResultOutput) WhitelistedLicenses() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) []string { return v.WhitelistedLicenses }).(pulumi.StringArrayOutput)
}

func (o LookupImageAssurancePolicyResultOutput) WhitelistedLicensesEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageAssurancePolicyResult) bool { return v.WhitelistedLicensesEnabled }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupImageAssurancePolicyResultOutput{})
}
