// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aquasec.Outputs
{

    [OutputType]
    public sealed class ApplicationScopeCategoryArtifact
    {
        public readonly ImmutableArray<Outputs.ApplicationScopeCategoryArtifactCf> Cfs;
        public readonly ImmutableArray<Outputs.ApplicationScopeCategoryArtifactFunction> Functions;
        public readonly ImmutableArray<Outputs.ApplicationScopeCategoryArtifactImage> Images;

        [OutputConstructor]
        private ApplicationScopeCategoryArtifact(
            ImmutableArray<Outputs.ApplicationScopeCategoryArtifactCf> cfs,

            ImmutableArray<Outputs.ApplicationScopeCategoryArtifactFunction> functions,

            ImmutableArray<Outputs.ApplicationScopeCategoryArtifactImage> images)
        {
            Cfs = cfs;
            Functions = functions;
            Images = images;
        }
    }
}
