// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aquasec.Outputs
{

    [OutputType]
    public sealed class GetApplicationScopeCategoryArtifactResult
    {
        public readonly ImmutableArray<Outputs.GetApplicationScopeCategoryArtifactCfResult> Cfs;
        public readonly ImmutableArray<Outputs.GetApplicationScopeCategoryArtifactFunctionResult> Functions;
        public readonly ImmutableArray<Outputs.GetApplicationScopeCategoryArtifactImageResult> Images;

        [OutputConstructor]
        private GetApplicationScopeCategoryArtifactResult(
            ImmutableArray<Outputs.GetApplicationScopeCategoryArtifactCfResult> cfs,

            ImmutableArray<Outputs.GetApplicationScopeCategoryArtifactFunctionResult> functions,

            ImmutableArray<Outputs.GetApplicationScopeCategoryArtifactImageResult> images)
        {
            Cfs = cfs;
            Functions = functions;
            Images = images;
        }
    }
}
