// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aquasec.Outputs
{

    [OutputType]
    public sealed class GetApplicationScopeCategoryWorkloadOResult
    {
        public readonly string Expression;
        public readonly ImmutableArray<Outputs.GetApplicationScopeCategoryWorkloadOVariableResult> Variables;

        [OutputConstructor]
        private GetApplicationScopeCategoryWorkloadOResult(
            string expression,

            ImmutableArray<Outputs.GetApplicationScopeCategoryWorkloadOVariableResult> variables)
        {
            Expression = expression;
            Variables = variables;
        }
    }
}
