// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aquasec.Outputs
{

    [OutputType]
    public sealed class GetEnforcerGroupsCommandResult
    {
        public readonly string Default;
        public readonly string Kubernetes;
        public readonly string Swarm;
        public readonly string Windows;

        [OutputConstructor]
        private GetEnforcerGroupsCommandResult(
            string @default,

            string kubernetes,

            string swarm,

            string windows)
        {
            Default = @default;
            Kubernetes = kubernetes;
            Swarm = swarm;
            Windows = windows;
        }
    }
}
