// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aquasec.Outputs
{

    [OutputType]
    public sealed class GetGatewaysGatewayResult
    {
        public readonly string Description;
        public readonly string GrpcAddress;
        public readonly string Hostname;
        /// <summary>
        /// The ID of this resource.
        /// </summary>
        public readonly string Id;
        public readonly string Logicalname;
        public readonly string PublicAddress;
        public readonly string Status;
        public readonly string Version;

        [OutputConstructor]
        private GetGatewaysGatewayResult(
            string description,

            string grpcAddress,

            string hostname,

            string id,

            string logicalname,

            string publicAddress,

            string status,

            string version)
        {
            Description = description;
            GrpcAddress = grpcAddress;
            Hostname = hostname;
            Id = id;
            Logicalname = logicalname;
            PublicAddress = publicAddress;
            Status = status;
            Version = version;
        }
    }
}
