// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aquasec.Outputs
{

    [OutputType]
    public sealed class ImageHistory
    {
        /// <summary>
        /// The image creation comment.
        /// </summary>
        public readonly string? Comment;
        /// <summary>
        /// The date and time when the image was registered.
        /// </summary>
        public readonly string? Created;
        public readonly string? CreatedBy;
        /// <summary>
        /// The ID of this resource.
        /// </summary>
        public readonly string? Id;
        public readonly int? Size;

        [OutputConstructor]
        private ImageHistory(
            string? comment,

            string? created,

            string? createdBy,

            string? id,

            int? size)
        {
            Comment = comment;
            Created = created;
            CreatedBy = createdBy;
            Id = id;
            Size = size;
        }
    }
}
