// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aquasec.Outputs
{

    [OutputType]
    public sealed class ImageAssurancePolicyScope
    {
        public readonly string? Expression;
        public readonly ImmutableArray<Outputs.ImageAssurancePolicyScopeVariable> Variables;

        [OutputConstructor]
        private ImageAssurancePolicyScope(
            string? expression,

            ImmutableArray<Outputs.ImageAssurancePolicyScopeVariable> variables)
        {
            Expression = expression;
            Variables = variables;
        }
    }
}
