// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aquasec.Inputs
{

    public sealed class ApplicationScopeCategoryGetArgs : Pulumi.ResourceArgs
    {
        [Input("artifacts")]
        private InputList<Inputs.ApplicationScopeCategoryArtifactGetArgs>? _artifacts;
        public InputList<Inputs.ApplicationScopeCategoryArtifactGetArgs> Artifacts
        {
            get => _artifacts ?? (_artifacts = new InputList<Inputs.ApplicationScopeCategoryArtifactGetArgs>());
            set => _artifacts = value;
        }

        [Input("entityScopes")]
        private InputList<Inputs.ApplicationScopeCategoryEntityScopeGetArgs>? _entityScopes;
        public InputList<Inputs.ApplicationScopeCategoryEntityScopeGetArgs> EntityScopes
        {
            get => _entityScopes ?? (_entityScopes = new InputList<Inputs.ApplicationScopeCategoryEntityScopeGetArgs>());
            set => _entityScopes = value;
        }

        [Input("infrastructures")]
        private InputList<Inputs.ApplicationScopeCategoryInfrastructureGetArgs>? _infrastructures;
        public InputList<Inputs.ApplicationScopeCategoryInfrastructureGetArgs> Infrastructures
        {
            get => _infrastructures ?? (_infrastructures = new InputList<Inputs.ApplicationScopeCategoryInfrastructureGetArgs>());
            set => _infrastructures = value;
        }

        [Input("workloads")]
        private InputList<Inputs.ApplicationScopeCategoryWorkloadGetArgs>? _workloads;
        public InputList<Inputs.ApplicationScopeCategoryWorkloadGetArgs> Workloads
        {
            get => _workloads ?? (_workloads = new InputList<Inputs.ApplicationScopeCategoryWorkloadGetArgs>());
            set => _workloads = value;
        }

        public ApplicationScopeCategoryGetArgs()
        {
        }
    }
}
