// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aquasec.Inputs
{

    public sealed class ApplicationScopeCategoryInfrastructureGetArgs : Pulumi.ResourceArgs
    {
        [Input("kubernetes")]
        private InputList<Inputs.ApplicationScopeCategoryInfrastructureKuberneteGetArgs>? _kubernetes;
        public InputList<Inputs.ApplicationScopeCategoryInfrastructureKuberneteGetArgs> Kubernetes
        {
            get => _kubernetes ?? (_kubernetes = new InputList<Inputs.ApplicationScopeCategoryInfrastructureKuberneteGetArgs>());
            set => _kubernetes = value;
        }

        [Input("os")]
        private InputList<Inputs.ApplicationScopeCategoryInfrastructureOGetArgs>? _os;
        public InputList<Inputs.ApplicationScopeCategoryInfrastructureOGetArgs> Os
        {
            get => _os ?? (_os = new InputList<Inputs.ApplicationScopeCategoryInfrastructureOGetArgs>());
            set => _os = value;
        }

        public ApplicationScopeCategoryInfrastructureGetArgs()
        {
        }
    }
}
