// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aquasec.Inputs
{

    public sealed class AquasecHostRuntimePolicyWindowsRegistryProtectionGetArgs : Pulumi.ResourceArgs
    {
        [Input("excludedPaths")]
        private InputList<string>? _excludedPaths;

        /// <summary>
        /// List of registry paths to be excluded from being protected.
        /// </summary>
        public InputList<string> ExcludedPaths
        {
            get => _excludedPaths ?? (_excludedPaths = new InputList<string>());
            set => _excludedPaths = value;
        }

        [Input("excludedProcesses")]
        private InputList<string>? _excludedProcesses;

        /// <summary>
        /// List of registry processes to be excluded from being protected.
        /// </summary>
        public InputList<string> ExcludedProcesses
        {
            get => _excludedProcesses ?? (_excludedProcesses = new InputList<string>());
            set => _excludedProcesses = value;
        }

        [Input("excludedUsers")]
        private InputList<string>? _excludedUsers;

        /// <summary>
        /// List of registry paths to be users from being protected.
        /// </summary>
        public InputList<string> ExcludedUsers
        {
            get => _excludedUsers ?? (_excludedUsers = new InputList<string>());
            set => _excludedUsers = value;
        }

        [Input("protectedPaths")]
        private InputList<string>? _protectedPaths;

        /// <summary>
        /// List of registry paths to be protected.
        /// </summary>
        public InputList<string> ProtectedPaths
        {
            get => _protectedPaths ?? (_protectedPaths = new InputList<string>());
            set => _protectedPaths = value;
        }

        [Input("protectedProcesses")]
        private InputList<string>? _protectedProcesses;

        /// <summary>
        /// List of registry processes to be protected.
        /// </summary>
        public InputList<string> ProtectedProcesses
        {
            get => _protectedProcesses ?? (_protectedProcesses = new InputList<string>());
            set => _protectedProcesses = value;
        }

        [Input("protectedUsers")]
        private InputList<string>? _protectedUsers;

        /// <summary>
        /// List of registry users to be protected.
        /// </summary>
        public InputList<string> ProtectedUsers
        {
            get => _protectedUsers ?? (_protectedUsers = new InputList<string>());
            set => _protectedUsers = value;
        }

        public AquasecHostRuntimePolicyWindowsRegistryProtectionGetArgs()
        {
        }
    }
}
