// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aquasec.Inputs
{

    public sealed class GetApplicationScopeCategoryEntityScopeVariableArgs : Pulumi.InvokeArgs
    {
        [Input("attribute", required: true)]
        public string Attribute { get; set; } = null!;

        [Input("value", required: true)]
        public string Value { get; set; } = null!;

        public GetApplicationScopeCategoryEntityScopeVariableArgs()
        {
        }
    }
}
