// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aquasec.Inputs
{

    public sealed class GetApplicationScopeCategoryWorkloadCfArgs : Pulumi.InvokeArgs
    {
        [Input("expression", required: true)]
        public string Expression { get; set; } = null!;

        [Input("variables")]
        private List<Inputs.GetApplicationScopeCategoryWorkloadCfVariableArgs>? _variables;
        public List<Inputs.GetApplicationScopeCategoryWorkloadCfVariableArgs> Variables
        {
            get => _variables ?? (_variables = new List<Inputs.GetApplicationScopeCategoryWorkloadCfVariableArgs>());
            set => _variables = value;
        }

        public GetApplicationScopeCategoryWorkloadCfArgs()
        {
        }
    }
}
