// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aquasec.Inputs
{

    public sealed class GetApplicationScopeCategoryInfrastructureKuberneteInputArgs : Pulumi.ResourceArgs
    {
        [Input("expression", required: true)]
        public Input<string> Expression { get; set; } = null!;

        [Input("variables")]
        private InputList<Inputs.GetApplicationScopeCategoryInfrastructureKuberneteVariableInputArgs>? _variables;
        public InputList<Inputs.GetApplicationScopeCategoryInfrastructureKuberneteVariableInputArgs> Variables
        {
            get => _variables ?? (_variables = new InputList<Inputs.GetApplicationScopeCategoryInfrastructureKuberneteVariableInputArgs>());
            set => _variables = value;
        }

        public GetApplicationScopeCategoryInfrastructureKuberneteInputArgs()
        {
        }
    }
}
