// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

/**
 * The data source `aquasec.getGateways` provides a method to query all gateways within the Aqua
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aquasec from "@pulumi/aquasec";
 *
 * const testgateway = aquasec.getGateways({});
 * export const gatewayData = testgateway;
 * export const gatewayName = testgateway.then(testgateway => testgateway.gateways?[0]?.id);
 * export const gatewayStatus = testgateway.then(testgateway => testgateway.gateways?[0]?.status);
 * export const gatewayDescription = testgateway.then(testgateway => testgateway.gateways?[0]?.description);
 * export const gatewayVersion = testgateway.then(testgateway => testgateway.gateways?[0]?.version);
 * export const gatewayHostname = testgateway.then(testgateway => testgateway.gateways?[0]?.hostname);
 * export const gatewayGrpcAddress = testgateway.then(testgateway => testgateway.gateways?[0]?.grpcAddress);
 * ```
 */
export function getGateways(opts?: pulumi.InvokeOptions): Promise<GetGatewaysResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("aquasec:index/getGateways:getGateways", {
    }, opts);
}

/**
 * A collection of values returned by getGateways.
 */
export interface GetGatewaysResult {
    readonly gateways: outputs.GetGatewaysGateway[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
